### ISSUE TITLE
Issue loading BSP

### ISSUE THREAD

**Issue by DavidKroncke** [llennoco22/Apex-mprt-importer-for-Blender#3]
So I have everything installed that I should, I have gotten to the minute mark on the video at this point. However the moment I try to put the BSP into Legion it fails.

**Comment by llennoco22** [comment]
The video is outdated (warning in the readme). Follow the readme instructions instead. This includes using Legion+ and exporting all the bsp_lump files. If issues persist after faithfully following those instructions, it would be a Legion+ side issue. This is simply the script for importing the output into Blender.
