### ISSUE TITLE
Errors using Apex mprt importer in blender 3.1 

### ISSUE THREAD

**Issue by Fardies999** [llennoco22/Apex-mprt-importer-for-Blender#4]
![image](https://user-images.githubusercontent.com/107644461/174138573-2432a757-9efc-494f-b0ee-80fd08c91df1.png)
I got this error when i tried importing a map in blender 3.1, Had to switch to blender 2.8 for it to work and still the "instancing" process is taking waaay too long (12 hours for 75 percent).
hopefully this helps fixing the issue and thank you for making this addon !

**Comment by llennoco22** [comment]
The error you see is actually a cast error, not from the map importer. I recommend getting the latest version of Cast for Blender 3.1. When using the map importer on BR maps, you need to use a radius. Apex BR maps are too large to import into Blender.
